# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Cedric Manouan
title: Cedric's Personal website
email: manouancedric@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

# twitter_username: cmDrStrange
# github_username:  dric2018

avatar: images/mimi.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: manouan@gmail.com
  github: dric2018
  instagram: unicorn22505
  twitter: cmDrStrange
permalink: /

# Build settings
markdown: kramdown
theme: minima

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

plugins:
  # - jekyll-feed
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
